-- Squashed baseline for the WMNY Shift Swap schema.
--
-- Replaces the original 16 migrations. Those could not build a database from
-- scratch: Prisma orders migrations by the numeric timestamp prefix, so the
-- fifteen hand-named 8-digit directories sorted ahead of the 14-digit
-- 20260401214939_init, init ran last, and the first migration applied failed
-- with 42P01 relation "users" does not exist. See
-- docs/migration-baseline-squash.md.
--
-- Generated by replaying all 16 migrations in dependency order (init first)
-- against an empty Postgres 16, then dumping the resulting schema. Verified
-- to reproduce that schema byte-for-byte on a clean database.
--
-- The last two statements are the partial unique indexes from
-- prisma/partial-indexes.sql. They cannot be expressed in schema.prisma, and
-- without them duplicate proposals return 201 instead of 409.
--
-- DO NOT deploy this without first running, on every live environment:
--   npx prisma migrate resolve --applied 20260720000000_baseline
-- vercel-build runs `prisma migrate deploy && next build`, so deploying it
-- unresolved fails with P3018 / 42710 and blocks every later deploy.

CREATE TYPE public."AgreementStatus" AS ENUM (
    'pending',
    'userA_confirmed',
    'accepted',
    'completed',
    'cancelled',
    'declined',
    'disputed'
);
CREATE TYPE public."ReportStatus" AS ENUM (
    'pending',
    'reviewed',
    'dismissed'
);
CREATE TYPE public."SwapCategory" AS ENUM (
    'work',
    'daysoff',
    'vacation',
    'open_work'
);
CREATE TYPE public."SwapStatus" AS ENUM (
    'open',
    'pending',
    'filled',
    'expired'
);
CREATE TYPE public."UserRole" AS ENUM (
    'operator',
    'depotRep',
    'admin',
    'subAdmin',
    'dispatcher'
);
CREATE TABLE public.announcements (
    id text NOT NULL,
    depot_id text NOT NULL,
    author_id text NOT NULL,
    body character varying(600) NOT NULL,
    pinned boolean DEFAULT false NOT NULL,
    expires_at timestamp(3) without time zone,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.audit_logs (
    id text NOT NULL,
    admin_id text NOT NULL,
    action text NOT NULL,
    target_id text,
    target_type text,
    detail text,
    ip text,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.blocks (
    id text NOT NULL,
    blocker_id text NOT NULL,
    blocked_id text NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.depots (
    id text NOT NULL,
    name text NOT NULL,
    code text NOT NULL,
    borough text NOT NULL,
    operator text NOT NULL,
    logo_url text
);
CREATE TABLE public.invite_codes (
    id text NOT NULL,
    code text NOT NULL,
    created_by text NOT NULL,
    used_by text,
    is_valid boolean DEFAULT true NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.messages (
    id text NOT NULL,
    swap_id text,
    from_user_id text NOT NULL,
    to_user_id text NOT NULL,
    text character varying(2000) NOT NULL,
    read boolean DEFAULT false NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.notifications (
    id text NOT NULL,
    user_id text NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    url text,
    read boolean DEFAULT false NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.push_subscriptions (
    id text NOT NULL,
    user_id text NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.reports (
    id text NOT NULL,
    swap_id text NOT NULL,
    reporter_id text NOT NULL,
    reason text,
    status public."ReportStatus" DEFAULT 'pending'::public."ReportStatus" NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.reputation (
    id text NOT NULL,
    user_id text NOT NULL,
    completed integer DEFAULT 0 NOT NULL,
    cancelled integer DEFAULT 0 NOT NULL,
    "noShow" integer DEFAULT 0 NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.reviews (
    id text NOT NULL,
    swap_id text NOT NULL,
    reviewer_id text NOT NULL,
    reviewed_id text NOT NULL,
    rating integer NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.saved_swaps (
    id text NOT NULL,
    user_id text NOT NULL,
    swap_id text NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.swap_agreements (
    id text NOT NULL,
    swap_id text NOT NULL,
    user_a_id text NOT NULL,
    user_b_id text NOT NULL,
    status public."AgreementStatus" DEFAULT 'pending'::public."AgreementStatus" NOT NULL,
    user_a_note character varying(500),
    user_b_note character varying(500),
    user_a_at timestamp(3) without time zone,
    user_b_at timestamp(3) without time zone,
    completed_at timestamp(3) without time zone,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(3) without time zone NOT NULL,
    accepted_at timestamp(3) without time zone,
    user_a_happened boolean,
    user_b_happened boolean,
    shift_date date
);
CREATE TABLE public.swaps (
    id text NOT NULL,
    user_id text NOT NULL,
    depot_id text NOT NULL,
    category public."SwapCategory" NOT NULL,
    status public."SwapStatus" DEFAULT 'open'::public."SwapStatus" NOT NULL,
    date date,
    details character varying(500) NOT NULL,
    contact text,
    run text,
    route text,
    start_time text,
    clear_time text,
    swing_start text,
    swing_end text,
    from_day text,
    from_date date,
    to_day text,
    to_date date,
    vacation_have text,
    vacation_want text,
    poster_name text NOT NULL,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(3) without time zone NOT NULL,
    archived_at timestamp(3) without time zone
);
CREATE TABLE public.users (
    id text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    depot_id text,
    language text DEFAULT 'en'::text NOT NULL,
    avatar_url text,
    verified boolean DEFAULT false NOT NULL,
    invited_by text,
    created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(3) without time zone NOT NULL,
    role public."UserRole" DEFAULT 'operator'::public."UserRole" NOT NULL,
    flexible_mode boolean DEFAULT false NOT NULL,
    flexible_since timestamp(3) without time zone,
    email_verify_token text,
    email_verify_expires timestamp(3) without time zone,
    terms_accepted_at timestamp(3) without time zone,
    terms_version text,
    login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp(3) without time zone,
    suspended_until timestamp(3) without time zone,
    last_active_at timestamp(3) without time zone,
    job_title text,
    depot_set_at timestamp(3) without time zone,
    verified_operator boolean DEFAULT false NOT NULL,
    dispatcher_verified boolean DEFAULT false NOT NULL,
    dispatcher_badge text,
    notification_prefs jsonb,
    quiet_end text,
    quiet_start text,
    signup_source text
);
ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_blocker_id_blocked_id_key UNIQUE (blocker_id, blocked_id);
ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.depots
    ADD CONSTRAINT depots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invite_codes
    ADD CONSTRAINT invite_codes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reputation
    ADD CONSTRAINT reputation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.saved_swaps
    ADD CONSTRAINT saved_swaps_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.swap_agreements
    ADD CONSTRAINT swap_agreements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.swaps
    ADD CONSTRAINT swaps_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE INDEX audit_logs_admin_id_idx ON public.audit_logs USING btree (admin_id);
CREATE INDEX audit_logs_created_at_idx ON public.audit_logs USING btree (created_at DESC);
CREATE INDEX blocks_blocked_id_idx ON public.blocks USING btree (blocked_id);
CREATE UNIQUE INDEX depots_code_key ON public.depots USING btree (code);
CREATE UNIQUE INDEX invite_codes_code_key ON public.invite_codes USING btree (code);
CREATE UNIQUE INDEX invite_codes_used_by_key ON public.invite_codes USING btree (used_by);
CREATE INDEX messages_from_user_id_to_user_id_created_at_idx ON public.messages USING btree (from_user_id, to_user_id, created_at DESC);
CREATE INDEX messages_swap_id_idx ON public.messages USING btree (swap_id);
CREATE INDEX messages_to_user_id_read_idx ON public.messages USING btree (to_user_id, read);
CREATE INDEX notifications_user_id_created_at_idx ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX notifications_user_id_read_idx ON public.notifications USING btree (user_id, read);
CREATE UNIQUE INDEX push_subscriptions_endpoint_key ON public.push_subscriptions USING btree (endpoint);
CREATE UNIQUE INDEX reputation_user_id_key ON public.reputation USING btree (user_id);
CREATE UNIQUE INDEX reviews_swap_id_reviewer_id_key ON public.reviews USING btree (swap_id, reviewer_id);
CREATE INDEX saved_swaps_user_id_idx ON public.saved_swaps USING btree (user_id);
CREATE UNIQUE INDEX saved_swaps_user_id_swap_id_key ON public.saved_swaps USING btree (user_id, swap_id);
CREATE INDEX swap_agreements_status_shift_date_idx ON public.swap_agreements USING btree (status, shift_date);
CREATE UNIQUE INDEX swap_agreements_swap_id_accepted_key ON public.swap_agreements USING btree (swap_id) WHERE (status = ANY (ARRAY['accepted'::public."AgreementStatus", 'userA_confirmed'::public."AgreementStatus"]));
CREATE UNIQUE INDEX swap_agreements_swap_user_pending_key ON public.swap_agreements USING btree (swap_id, user_a_id) WHERE (status = 'pending'::public."AgreementStatus");
CREATE INDEX swaps_archived_at_idx ON public.swaps USING btree (archived_at);
CREATE INDEX swaps_depot_id_status_created_at_idx ON public.swaps USING btree (depot_id, status, created_at DESC);
CREATE INDEX swaps_user_id_created_at_idx ON public.swaps USING btree (user_id, created_at);
CREATE INDEX swaps_user_id_status_idx ON public.swaps USING btree (user_id, status);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_depot_id_fkey FOREIGN KEY (depot_id) REFERENCES public.depots(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_blocked_id_fkey FOREIGN KEY (blocked_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_blocker_id_fkey FOREIGN KEY (blocker_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.invite_codes
    ADD CONSTRAINT invite_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.invite_codes
    ADD CONSTRAINT invite_codes_used_by_fkey FOREIGN KEY (used_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_swap_id_fkey FOREIGN KEY (swap_id) REFERENCES public.swaps(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_swap_id_fkey FOREIGN KEY (swap_id) REFERENCES public.swaps(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.reputation
    ADD CONSTRAINT reputation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_reviewed_id_fkey FOREIGN KEY (reviewed_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_swap_id_fkey FOREIGN KEY (swap_id) REFERENCES public.swaps(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.saved_swaps
    ADD CONSTRAINT saved_swaps_swap_id_fkey FOREIGN KEY (swap_id) REFERENCES public.swaps(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.saved_swaps
    ADD CONSTRAINT saved_swaps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.swap_agreements
    ADD CONSTRAINT swap_agreements_swap_id_fkey FOREIGN KEY (swap_id) REFERENCES public.swaps(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.swap_agreements
    ADD CONSTRAINT swap_agreements_user_a_id_fkey FOREIGN KEY (user_a_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.swap_agreements
    ADD CONSTRAINT swap_agreements_user_b_id_fkey FOREIGN KEY (user_b_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.swaps
    ADD CONSTRAINT swaps_depot_id_fkey FOREIGN KEY (depot_id) REFERENCES public.depots(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.swaps
    ADD CONSTRAINT swaps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_depot_id_fkey FOREIGN KEY (depot_id) REFERENCES public.depots(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;
